# Generated by Django 5.0.6 on 2024-05-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefas',
            options={'verbose_name_plural': 'Tarefas'},
        ),
    ]
